version: '3.1'

services:
    main:
        build:
            .\main
        restart: always
        ports:
            - 10000:10000
    login:
        build:
            .\login-microservice
        restart: always
        ports:
            - 11000:11000
        volumes:
            - /login-microservice:/login-microservice/
    documents:
        build:
            .\documents-microservice
        restart: always
        ports:
            - 12000:12000

    # user:
    #     build:
    #         .\user-microservice
    #     restart: always
    #     ports:
    #         - 12000:12000
